name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies for flake8
        run: python -m pip install flake8

      - name: linting tests
        run: flake8 tests/ --config tests/.flake8

      #- name: install dependencies for unittests
      #  run: python -m pip install pyzmq pmt numpy

      #- name: run unittests
      #  run: python -m unittest -v tests/test_DecodeALS162.py
